name: Run
on:
  push:
    path: "*"

  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Repository
        uses: actions/checkout@main

      - name: Run
        uses: GabrielBB/xvfb-action@v1
        with:
          run: |
            mkdir -p downloads
            cd downloads
            sudo firefox https://apkcombo.com & sleep 15
            URL1=$(curl -s https://apkcombo.com/youtube/com.google.android.youtube/download/apk | grep -i "https://download.apkcombo.com/com.google.android.youtube/YouTube_17.49.37_apkcombo.com.apk" | cut -b 9- | awk '{print $1}' | tr -d '"' | sort -u) && URL2=$(curl -s https://apkcombo.com/checkin) && wget -nv "$URL1&$URL2"

      - name: Upload ReVanced Applications
        uses: termux/upload-release-action@master
        with:
          repo_name: ${{ github.repository }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: "${{ github.run_id }}"
          tag: "${{ github.run_id }}"
          checksums: sha256
          file: downloads/*
          overwrite: true
          file_glob: true
          prerelease: false
