name: Run
on:
  push:
    path: "*"

  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@main

      - name: Run
        run: |
          mkdir -p downloads
          cd downloads
          VERSION=17.49.37
          wget $(curl -s https://apkflash.com/apk/app/com.google.android.youtube/youtube/download/"$VERSION" | grep -i "https://download.apkflash.com/com.google.android.youtube/youtube_"$VERSION"_apkflash.com.apk" | cut -b 26- | awk '{print $1}' | tr -d '"' | sort -u)

      - name: Upload ReVanced Applications
        uses: termux/upload-release-action@master
        with:
          repo_name: ${{ github.repository }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: "${{ github.run_id }}"
          tag: "${{ github.run_id }}"
          checksums: sha256
          file: downloads/*
          overwrite: true
          file_glob: true
          prerelease: false
