name: Run
on:
  push:
    path: "*"

  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@main

      - name: Run
        run: |
          URL=http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4
          curl -X GET https://upstream.to/api/upload/url?key=47374lfd0yjehhjieip3k&url="$URL"

      - name: Upload ReVanced Applications
        uses: termux/upload-release-action@master
        with:
          repo_name: ${{ github.repository }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: "${{ github.run_id }}"
          tag: "0.2"
          checksums: sha256
          file: downloads/*
          overwrite: true
          file_glob: true
          prerelease: false
