name: Run
on:
  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Repository
        uses: actions/checkout@main

      - name: Run
        run: |
          URL=$(curl -X GET https://upstream.to/api/upload/server?key=47374lfd0yjehhjieip3k | jq -r '.result')
          FILECODE=$(curl -X POST -F 'key=47374lfd0yjehhjieip3k' -F 'file=@video.mp4' "$URL" | awk '{print $8}' | cut -b 10- | tr -d '":,')
          echo "upstream.to/'$FILECODE'"
