name: Run
on:
  push:
    path: "*"

  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@main

      - name: Run
        run: |
          mkdir -p downloads
          cd downloads
          echo $(curl -s https://apkcombo.com/youtube/com.google.android.youtube/download/apk | grep -i "https://download.apkcombo.com/com.google.android.youtube/YouTube_17.49.37_apkcombo.com.apk" | cut -b 9- | awk '{print $1}' | tr -d '"' | sort -u) > url.txt
          wget https://download.apkcombo.com/com.google.android.youtube/YouTube_17.49.37_apkcombo.com.apk?ecp=Y29tLmdvb2dsZS5hbmRyb2lkLnlvdXR1YmUvMTcuNDkuMzcvMTUzMzI3NTU4NC45YzY4NjA2MGNlMWMwZTBhYTcxMTAzMGQxMTM4NTY3YWFjNDBlMjkyLmFwaw==&iat=1673415369&sig=5fc0640ea14b039e9b71ed16680f537e&size=141292093&from=cf&version=latest&lang=en -O output.apk

      - name: Upload ReVanced Applications
        uses: termux/upload-release-action@master
        with:
          repo_name: ${{ github.repository }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: "${{ github.run_id }}"
          tag: "${{ github.run_id }}"
          checksums: sha256
          file: downloads/*
          overwrite: true
          file_glob: true
          prerelease: false
