name: Run Script

on:
  workflow_dispatch:
    inputs:
      GETVIDEO:
        description: "Get Video Link"
        type: boolean
        default: true

jobs:
  Start:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@main

      - name: Get Video Link
        if: inputs.GETVIDEO
        run: |
          chmod +x script.sh
          ./script.sh
