name: Run
on:
  push:
    path: "assets/url.txt"

  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@main

      - name: Run
        run: |
          chmod +x script.sh
          ./script.sh
