name: Run
on:
  push:
    path: "*"

  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@main

      - name: Run
        run: |
          mkdir downloads
          cd downloads
          gh release download -R revanced/revanced-cli -p *.jar
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Upload ReVanced Applications
        uses: termux/upload-release-action@master
        with:
          repo_name: ${{ github.repository }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: "${{ github.run_id }}"
          tag: "${{ github.run_id }}"
          checksums: sha256
          file: downloads/*
          overwrite: true
          file_glob: true
          prerelease: false
